# Generated by Django 4.2.1 on 2023-05-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('prodid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=20, null=True)),
                ('model_name', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('date_of_manf', models.DateField(blank=True, null=True)),
                ('processor', models.CharField(blank=True, max_length=20, null=True)),
                ('storage', models.CharField(blank=True, max_length=5, null=True)),
                ('ram', models.CharField(blank=True, max_length=5, null=True)),
                ('os', models.CharField(blank=True, max_length=30, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('screen_type', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'laptop',
                'managed': False,
            },
        ),
    ]
