# Generated by Django 4.2.1 on 2023-05-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('prodid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=20)),
                ('price', models.FloatField(null=True)),
                ('date_of_manf', models.DateField(null=True)),
                ('processor', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=5)),
                ('size', models.IntegerField(null=True)),
                ('screen_type', models.CharField(max_length=5)),
                ('OS', models.CharField(max_length=30)),
                ('Storage', models.CharField(max_length=5)),
            ],
        ),
    ]
