# Generated by Django 4.2.1 on 2023-05-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('emailid', models.CharField(max_length=30, null=True)),
                ('ph_no', models.IntegerField(null=True)),
                ('dob', models.DateField(null=True)),
            ],
        ),
    ]
