# Generated by Django 4.2.1 on 2023-05-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0003_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=10)),
                ('prodid', models.CharField(max_length=10)),
                ('brand_name', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('date_of_manf', models.DateField()),
                ('processor', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=5)),
                ('size', models.IntegerField(null=True)),
                ('screen_type', models.CharField(max_length=5)),
                ('OS', models.CharField(max_length=30)),
                ('Storage', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'laptop_logs',
            },
        ),
    ]
