# Generated by Django 4.2.1 on 2023-05-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0005_delete_laptoplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('brand_name', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=20)),
                ('price', models.FloatField(blank=True, null=True)),
                ('date_of_manf', models.DateField(blank=True, null=True)),
                ('processor', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=5)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('screen_type', models.CharField(max_length=5)),
                ('OS', models.CharField(max_length=30)),
                ('Storage', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.laptop')),
            ],
            options={
                'db_table': 'laptop_logs',
            },
        ),
    ]
