# Generated by Django 4.2.1 on 2023-05-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0006_laptoplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('techid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=20, null=True)),
                ('tusername', models.CharField(max_length=30, null=True)),
                ('hiredate', models.DateField(null=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('salary', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LaptopLog',
        ),
    ]
