# Generated by Django 4.2.1 on 2023-05-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0007_technician_delete_laptoplog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='technician',
            table='laptop_technician',
        ),
    ]
