# Generated by Django 4.2.1 on 2023-05-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0008_alter_technician_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('reqid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('custid', models.CharField(max_length=10)),
                ('date_of_req', models.DateField()),
                ('repair_type', models.CharField(max_length=30)),
                ('user_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
