# Generated by Django 4.2.1 on 2023-05-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_laptop_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='os',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='storage',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='brand_name',
            field=models.CharField(blank=True, default='tbd', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='date_of_manf',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model_name',
            field=models.CharField(blank=True, default='tbd', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(blank=True, default='tbd', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.CharField(blank=True, default='tbd', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_type',
            field=models.CharField(blank=True, default='tbd', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='laptop',
            table=None,
        ),
        migrations.AddField(
            model_name='laptop',
            name='OS',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='laptop',
            name='Storage',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
