# Generated by Django 4.2.1 on 2023-05-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_remove_laptop_os_remove_laptop_storage_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='laptop',
            table='laptop',
        ),
    ]
