# Generated by Django 4.2.1 on 2023-05-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_laptop_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('emailid', models.CharField(blank=True, max_length=30, null=True)),
                ('ph_no', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
